import turtle

window =turtle.Screen()
window.title("Hello turtle")
turtle.shape("turtle")
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(35)
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(35)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(80)
window.exitonclick()